%FLAGS  = 0
%AX     = 1
%BX     = 2
%CX     = 3
%DX     = 4
%SI     = 5
%DI     = 6
%BP     = 7
%DS     = 8
%ES     = 9
%F1		  = 59
%F2		  = 60
%F3     = 61
%F4     = 62
%F5     = 63
%F6     = 64
%F7     = 65
%F8     = 66
%F9     = 67
%F10    = 68
%AltF1  = 104
%AltF2  = 105
%AltF3  = 106
%AltF4  = 107
%AltF5  = 108
%AltF6  = 109
%AltF7  = 110
%AltF8  = 111
%AltF9  = 112
%AltF10 = 113
%Home   = 71
%UpAr   = 72
%PgUp   = 73
%LfAr   = 75
%RtAr   = 77
%End    = 79
%DnAr   = 80
%PgDn   = 81
%Del    = 83
%False  = 0
%True   = -1
%Bsp    = 8
%Lfd		= 10
%Ent    = 13
%Tag		= 16
%Esc    = 27
%Spc    = 32

%Black	= 0
%Blue		= 1
%Green	= 2
%Cyan		= 3
%Red		= 4
%White	= 7
%Grey		= 8
%LCyan	= 11
%LRed		= 12
%Yellow	= 14
%HWhite	= 15
%Flash	= 16

%HeadLine = 17
%SelLine  = 19
%ActLine  = 21

%TopLeft1 = &H0101:%BottomRight1 = &H144E
%TopLeft2 = &H0101:%BottomRight2 = &H0E4E
%TopLeft3 = &H1600:%BottomRight3 = &H194F
